---
# This is a Slskd playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Slskd
      community.docker.docker_container:
        name: "{{ slskd_container_name }}"
        state: absent
      register: result

    - name: Check Slskd is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
